# Generated by Django 2.2 on 2019-04-06 18:05
from django.conf import settings
import django.db.models.deletion
from django.db import migrations, models

import oauth2_provider.generators
import oauth2_provider.validators
from oauth2_provider.settings import oauth2_settings


class Migration(migrations.Migration):

    dependencies = [
        ('oauth2_provider', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grant',
            name='code_challenge',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='grant',
            name='code_challenge_method',
            field=models.CharField(blank=True, choices=[('plain', 'plain'), ('S256', 'S256')], default='', max_length=10),
        ),

        # mcdaniel july-2020: juniper upgrade.
        # these migrations were created in two individual "makemigrations" operations in calendar 2017,
        # and then later squashed into 0001_initial.py, which is omitted in Hawthorn->Juniper since oauth2_provider
        # is already present.
        #
        # Furthermore, it doesn't seem viable to uninstall/re-install the package bc of legacy data in the Hawthorn
        # databases.
        migrations.AddField(
            model_name='AccessToken',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AddField(
            model_name='AccessToken',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='AccessToken',
            name='source_refresh_token',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=oauth2_settings.REFRESH_TOKEN_MODEL, related_name="refreshed_access_token"),
        ),

        migrations.AddField(
            model_name='Application',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AddField(
            model_name='Application',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
       migrations.AddField(
            model_name='Grant',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AddField(
            model_name='Grant',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),

        migrations.AddField(
            model_name='RefreshToken',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AddField(
            model_name='RefreshToken',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='RefreshToken',
            name='revoked',
            field=models.DateTimeField(null=True),
        ),
    ]